# Generated by Django 5.2 on 2025-04-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Jeep', 'Jeep'), ('Dodge', 'Dodge'), ('Ram', 'Ram'), ('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Mitsubishi', 'Mitsubishi'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Volvo', 'Volvo'), ('Land Rover', 'Land Rover'), ('Jaguar', 'Jaguar'), ('Mini', 'Mini'), ('Chrysler', 'Chrysler'), ('GMC', 'GMC'), ('Acura', 'Acura'), ('Infiniti', 'Infiniti'), ('Genesis', 'Genesis'), ('Alfa Romeo', 'Alfa Romeo'), ('Suzuki', 'Suzuki'), ('Tata Motors', 'Tata Motors'), ('Saab', 'Saab'), ('Skoda', 'Skoda'), ('Pagani', 'Pagani'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('Maserati', 'Maserati'), ('Bugatti', 'Bugatti'), ('Tesla', 'Tesla'), ('Lucid Motors', 'Lucid Motors'), ('BYD', 'BYD'), ('Geely', 'Geely'), ('Changan', 'Changan'), ('Perodua', 'Perodua'), ('Haval', 'Haval')], default='Toyota', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('year_model', models.IntegerField()),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Wagon', 'Wagon'), ('Crossover', 'Crossover'), ('Sports Car', 'Sports Car'), ('Electric Car', 'Electric Car'), ('Hybrid Car', 'Hybrid Car'), ('Luxury Car', 'Luxury Car'), ('Off-Road Vehicle', 'Off-Road Vehicle')], default='Sedan', max_length=50)),
                ('description', models.TextField()),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('buy_price', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('status', models.CharField(choices=[('Available to Sale', 'Available to Sale'), ('In Inventory', 'In Inventory'), ('Sold', 'Sold')], default='Available to Sale', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('expense_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
