# Generated by Django 5.2 on 2025-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_expenses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sell_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
